### PR TITLE
Fix bug of interviews having conflicting timing for applicant

### LINKED ISSUE #101: Handle errors occuring from duplicate timeslots in interviews
Right now, it is possible to add 2 interviews at the exact same time, for 2 different roles, for the same candidate. We should do the error checking either in applicant or the interview class.

We might do it in the applicant class if we decide to link applicant with the interview, so that an applicant can see all his/her interviews in the next iteration.

### PR DESCRIPTION
**Pull request by goalfix**
An applicant cannot have interviews within the same 1 hour timeslot.

For example, if he has an interview at 11am, he cannot have an interview (regardless of position) from 10.01am till 11.59am. Thus, we will block adding of interviews during that time frame.

Could you guys help me check whether the scheduling logic should be implemented in `Interview` or `UniqueInterviewList`?
Can I deprecate `hasInterview` in `AddInterviewCommand` as well? Seems like a subset to me.

Closes #101

### CODE REVIEW

File: src/main/java/seedu/address/model/interview/Interview.java [hunk 1]
```diff
@@ -61,6 +62,15 @@ public boolean isInterviewForPosition(Position p) {
         return position.isSamePosition(p);
     }
 
+    /**
+     * Checks if the given interview will conflict with the current interview.
+     */
+    public boolean isConflictingInterview(Interview i) {
+        return i.isInterviewForApplicant(this.applicant)
+                && !(i.date.isBefore(this.date.minus(59, ChronoUnit.MINUTES))
+                        || i.date.isAfter(this.date.plusMinutes(59)));
```
Comment (likeabowx) [inline src/main/java/seedu/address/model/interview/Interview.java:71]: Does the `minusMinutes(long minutes)` method for LocalDateTime not work in this case? Just for consistency

Comment (likeabowx) [inline src/main/java/seedu/address/model/interview/Interview.java:71]: I understand the logic here but maybe can split into a few lines for better readability? It may not be very intuitive for a first time reader to understand

**Review by likeabowx — CHANGES_REQUESTED** [review]
The logic works for checking if an applicant has a clashing interview time when adding an interview, just a small comment made. 

However, the `EditInteviewCommand` will have to be updated to do this check as well. @goalfix do you want to do it? Or i can do it too

**Comment by goalfix** [comment]
Hey @likeabowx, thanks for your comments. I have made the changes you suggested above.
Also, I have added the logic into the `EditInterviewCommand`, so no need for a separate PR.

Thanks!

**Review by likeabowx — APPROVED** [review]
LGTM, thanks for checking when editing interviews as well!
