### PR TITLE
Prevent toggling of interview status between pass and fail

### LINKED ISSUE #176: Disallowing states to be toggled for interview
Currently, states between `pass`/`fail`/`accept`/`reject` can be toggled between interviews. This should not be the case (as it would complicate how `PositionOffers` are being handed out.

### PR DESCRIPTION
**Pull request by goalfix**
Closes #176

### CODE REVIEW

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 1]
```diff
@@ -15,10 +15,13 @@
...
-            + "as the number of current offers will exceed the number of available positions!";
-    public static final String MESSAGE_INTERIVEW_CANNOT_BE_ACCEPTED = "The interview cannot be accepted, "
-            + "as it has not been passed yet!";
-    public static final String MESSAGE_INTERIVEW_CANNOT_BE_REJECTED = "The interview cannot be rejected, "
-            + "as it has not been passed yet!";
+    public static final String MESSAGE_INTERVIEW_CANNOT_BE_PASSED = "The interview cannot be passed, "
+            + "as the number of current offers will exceed the number of available positions or because the status"
+            + " has been modified and it is not pending";
+    public static final String MESSAGE_INTERVIEW_CANNOT_BE_FAILED = "The interview cannot be failed, "
+            + "since it's status has already been modified and it is not pending";
```
Comment (likeabowx) [inline src/main/java/seedu/address/commons/core/Messages.java:22]: Similar to above, maybe can be something like `Only pending interviews can be failed` or `You cannot fail an interview that has already been passed`

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 2]
```diff
@@ -15,10 +15,13 @@
...
     public static final String MESSAGE_PERSONS_LISTED_OVERVIEW = "%1$d persons listed!";
-    public static final String MESSAGE_INTERIVEW_CANNOT_BE_PASSED = "The interview cannot be passed, "
-            + "as the number of current offers will exceed the number of available positions!";
-    public static final String MESSAGE_INTERIVEW_CANNOT_BE_ACCEPTED = "The interview cannot be accepted, "
-            + "as it has not been passed yet!";
-    public static final String MESSAGE_INTERIVEW_CANNOT_BE_REJECTED = "The interview cannot be rejected, "
-            + "as it has not been passed yet!";
+    public static final String MESSAGE_INTERVIEW_CANNOT_BE_PASSED = "The interview cannot be passed, "
+            + "as the number of current offers will exceed the number of available positions or because the status"
+            + " has been modified and it is not pending";
```
Comment (likeabowx) [inline src/main/java/seedu/address/commons/core/Messages.java:20]: I feel that `status had been modified` is kind of confused as it sounds like the user can edit the status directly. Maybe just `or it is not pending` will do?

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 3]
```diff
@@ -15,10 +15,13 @@
...
+    public static final String MESSAGE_INTERVIEW_CANNOT_BE_FAILED = "The interview cannot be failed, "
+            + "since it's status has already been modified and it is not pending";
+    public static final String MESSAGE_INTERVIEW_CANNOT_BE_ACCEPTED = "The interview cannot be accepted, "
+            + "as it does not have a Passed status!";
```
Comment (likeabowx) [inline src/main/java/seedu/address/commons/core/Messages.java:24]: `Only passed interviews can be accepted` or something?

File: src/main/java/seedu/address/commons/core/Messages.java [hunk 4]
```diff
@@ -15,10 +15,13 @@
...
+    public static final String MESSAGE_INTERVIEW_CANNOT_BE_REJECTED = "The interview cannot be rejected, "
+            + "as it does not have a Passed status!";
```
Comment (likeabowx) [inline src/main/java/seedu/address/commons/core/Messages.java:26]: Similar to above

**Review by likeabowx — APPROVED** [review]
LGTM, it is important to add these additional checks for correctness of the interview flow. Added some suggestions for the messages for your consideration

File: src/main/java/seedu/address/commons/core/Messages.java (hunk 1 above)
Comment (goalfix) [reply src/main/java/seedu/address/commons/core/Messages.java:22]: I'll adopt the first one! The second suggestion would be problematic since this is the default error message would appear if the status is `accepted` or `rejected` which is one status ahead of this stage. Thanks @likeabowx !
